version: '3.8'
services:
  e2e-tests:
    build: .
    environment:
      - CI=true
      - BASE_URL=https://demoqa.com
    volumes:
      - ./test-results:/test-results
      - ./playwright-report:/playwright-report
    shm_size: '2gb'
