version: '3.8'

services:
  e2e-tests:
    image: mcr.microsoft.com/playwright:v1.28.1-focal
    container_name: playwright-docker-demo-e2e-tests
    volumes:
      - .:/app
    working_dir: /app
    command: npm run test:ci
    environment:
      - CI=true
