version: '3.8'

services:
  e2e-tests:
    build: .
    container_name: playwright-tests
    volumes:
      - ./test-results:/e2e-tests/test-results
      - ./playwright-report:/e2e-tests/playwright-report
    environment:
      - CI=true