version: 2.1

orbs:
  docker: circleci/docker@2.1.1
  browser-tools: circleci/browser-tools@1.4.1

jobs:
  e2e-tests:
    docker:
    - image: mcr.microsoft.com/playwright:v1.41.0-focal
    resource_class: large

    steps:
    - checkout

    - setup_remote_docker:
        docker_layer_caching: true

    - run:
        name: Install dependencies
        command: |
          npm ci
          npx playwright install chrome

    - run:
        name: Run E2E Tests
        command: npm run test:ci

    - store_test_results:
        path: test-results

    - store_artifacts:
        path: playwright-report
        destination: playwright-report

    - store_artifacts:
        path: test-results
        destination: test-results

workflows:
  version: 2
  test:
    jobs:
    - e2e-tests
