version: 2.1

orbs:
  docker: circleci/docker@2.1.1
  browser-tools: circleci/browser-tools@1.4.1

jobs:
  e2e-tests:
    docker:
    - image: cimg/node:16.14-browsers # Imagen adecuada para Node.js y Playwright
    resource_class: large # Se mantiene el uso de una clase de recursos 'large', ajusta según tus necesidades
    steps:
    - checkout
    - setup_remote_docker:
        docker_layer_caching: true # Habilita la caché de capas de Docker para optimizar la ejecución
    - run:
        name: Build Docker image
        command: docker-compose build
    - run:
        name: Run E2E Tests
        command: docker-compose up -d e2e-tests
    - run:
        name: Run Tests in Docker container
        command: docker exec e2e-tests npm run test:ci
    - run:
        name: Copy test results
        when: always
        command: |
          docker cp e2e-tests:/app/test-results ./test-results
          docker cp e2e-tests:/app/playwright-report ./playwright-report
    - store_test_results:
        path: test-results
    - store_artifacts:
        path: playwright-report
        destination: playwright-report

workflows:
  version: 2
  test-and-deploy:
    jobs:
    - e2e-tests:
        filters:
          branches:
            only: /.*/ # Esto permite que CircleCI ejecute el pipeline en todas las ramas
